export const USER_SIGNIN_SAGA = "USER_SIGNIN_SAGA";
export const PROJECT_CATEGORY_SAGA = "PROJECT_CATEGORY_SAGA";

export const ADD_HISTORY = "ADD_HISTORY";
export const LOGIN_ACTION = "LOGIN_ACTION";
