export const USER_SIGNIN_SAGA = "USER_SIGNIN_SAGA";

export const GET_ADD_USER_SAGA = "GET_ADD_USER_SAGA";

export const ADD_USER_PROJECT_SAGA = "ADD_USER_PROJECT_SAGA";

export const REMOVE_USER_PROJECT_SAGA = "REMOVE_USER_PROJECT_SAGA";

export const PROJECT_CATEGORY_SAGA = "PROJECT_CATEGORY_SAGA";

export const ADD_HISTORY = "ADD_HISTORY";
export const LOGIN_ACTION = "LOGIN_ACTION";
