export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_DRAWER_EDIT_FORM = "OPEN_DRAWER_EDIT_FORM";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const OPEN_DRAWER_CREATE_FORM = "OPEN_DRAWER_CREATE_FORM";
