export const GET_LIST_PROJECT = "GET_LIST_PROJECT";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const PUT_PROJECT_DETAIL = "PUT_PROJECT_DETAIL";
